{% set version = "2.0.3" %}

package:
  name: responder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/responder/responder-{{ version }}.tar.gz
  sha256: 2a7e271fa9158c7388446c6f027ebc8ca424fbeef29e731fede41f2939606929

build:
  number: 0
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - responder = responder.cli:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - starlette =0.12
    - uvicorn >=0.7,<0.9
    - aiofiles
    - pyyaml
    - requests
    - graphene <3.0
    - graphql-server-core >=1.1
    - jinja2
    - parse
    - uvloop  # [not win]
    - rfc3986
    - python-multipart
    - chardet
    - apispec >=1.0.0b1
    - marshmallow
    - asgiref
    - whitenoise
    - docopt
    - itsdangerous
    - requests-toolbelt
    - apistar

test:
  imports:
    - responder
  commands:
    - responder --help

about:
  home: https://github.com/taoufik07/responder
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A familiar HTTP Service Framework for Python'
  doc_url: http://python-responder.org/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
