{% set version = "2.0.5" %}

package:
  name: responder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/responder/responder-{{ version }}.tar.gz
  sha256: 92cd3daf9d5c58f9c5ad40a2cd310af619e6bd66dab6eb45501c26d1758afada

build:
  number: 0
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - responder = responder.cli:cli

requirements:
  host:
    - python
    - pip
  run:
    - aiofiles
    - apispec >=1.0.0b1
    - apistar
    - chardet
    - docopt
    - graphene <3.0
    - graphql-server-core >=1.1
    - itsdangerous
    - jinja2
    - marshmallow
    - python
    - python-multipart
    - pyyaml
    - requests
    - requests-toolbelt
    - rfc3986
    - starlette =0.12
    - uvicorn =0.10
    - uvloop  # [not win]
    - whitenoise

test:
  imports:
    - responder
  commands:
    - responder --help

about:
  home: https://github.com/taoufik07/responder
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A familiar HTTP Service Framework for Python'
  doc_url: http://python-responder.org/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
