{% set version = "1.3.1" %}

package:
  name: responder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/responder/responder-{{ version }}.tar.gz
  sha256: a8936a250620f99aa8f88813963d433f32c82acba81f1b45ae23f3dd84a3a219

build:
  number: 0
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - responder = responder.cli:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - starlette =0.10
    - uvicorn
    - aiofiles
    - pyyaml
    - requests
    - graphene
    - graphql-server-core >=1.1
    - jinja2
    - parse
    - uvloop  # [not win]
    - rfc3986
    - python-multipart
    - chardet
    - apispec >=1.0.0b1
    - marshmallow
    - asgiref
    - whitenoise
    - docopt
    - itsdangerous
    - requests-toolbelt
    - apistar

test:
  imports:
    - responder
  commands:
    - responder --help

about:
  home: https://github.com/kennethreitz/responder/
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'A familiar HTTP Service Framework for Python'
  doc_url: http://python-responder.org/en/latest/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
