appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: W/pqgFMrtCFguPmJ77iRS4NxShaPTo8b0Xvm2qcHxCIHt8Zw2BEiQqq6v7IIP+ZKzdVmz3SQCWwkZECgHXRCpKoQmD4ogbjlEGOjv+lj4rWd9UvLDBwbNKtNkLdlBqZZfOvaPkIZe45McyOHw11eMWQAYUg86DkWrCN5Q0GGF9+NS9BfYtJTSAuZrA5bvzFejyI8T7TUfex5rdzzsfTY17XcBJ4fDayzWox5bIkpAnaxuUpzJhMhtyprAHjOq5a5/ik+aKE6SmN0Q+yKj6RBxzbq361HRErRPuDFADQ9flUhZ9c0YA/DtnR+RIkrolbtoe1U3Y6WG5+7U7np3P80x8WqB087M8oGX+jQRhhrId8x/KzWn2cnC4PV+uq929uLumQbtsfDNZ80KKiZyIoPug+H9SX7mqx2AuhRG1cHlYchLnL9bexcwnGtul/pqszt15cjCBo4CHTRYEWnuv7n1z3ACMIsPpsqWCIpsnd/178/qXGF//vYRBhKLWgkAHeRSyt/dQPNup2bIGvWrdM5drHJVAmXJjA25KRXS+UVw+ESqndvHlxsRPnkyzBtaGJMVVJiUFzehTPzqb/eCN1nnKOX+pIEHaW1bMXu6HSMDmlRgksWw2NZZqElnl31TTPguNfWxNaXrxa8b9252eCpTM7nVZh2BLTkRtgjrO7WGdw=}
